name: Deploy to GoDaddy (spinner)
on:
  push:
    branches: [ main ]   # change if your default branch isn't 'main'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Build frontend
        working-directory: frontend
        run: |
          npm ci
          npm run build

      # Upload the built SPA
      - name: Upload FRONTEND (dist/) to /public_html/spinner/
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          server: ${{ secrets.SFTP_HOST }}
          username: ${{ secrets.SFTP_USER }}
          password: ${{ secrets.SFTP_PASS }}
          port: ${{ secrets.SFTP_PORT || 22 }}
          local_path: ./frontend/dist/*
          remote_path: /public_html/spinner

      # Upload SPA .htaccess (for client-side routing like /game/<slug>)
      - name: Upload SPA .htaccess
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          server: ${{ secrets.SFTP_HOST }}
          username: ${{ secrets.SFTP_USER }}
          password: ${{ secrets.SFTP_PASS }}
          port: ${{ secrets.SFTP_PORT || 22 }}
          local_path: ./frontend/.htaccess
          remote_path: /public_html/spinner

      # Upload PHP API
      - name: Upload API (PHP) to /public_html/spinner/api/
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          server: ${{ secrets.SFTP_HOST }}
          username: ${{ secrets.SFTP_USER }}
          password: ${{ secrets.SFTP_PASS }}
          port: ${{ secrets.SFTP_PORT || 22 }}
          local_path: ./api/*
          remote_path: /public_html/spinner/api
