// ...existing code...
export interface GameSettings {
  // ...existing code...
  backgroundMode?: 'solid' | 'gradient' | 'image';
  backgroundImageUrl?: string;
  // ...existing code...
}
// ...existing code...